---
title: "Blog: Project 1 Review Blog"
author: "Michael Bradshaw"
date: "`r Sys.Date()`" 
---

```{r setup, eval=TRUE, echo=FALSE}
knitr::opts_chunk$set(fig.path = "../images/")
```

```{r createblog, eval=FALSE, echo=FALSE}
rmarkdown::render(
  input = "C://Users//mbradshaw//OneDrive - Research Triangle Institute//Documents//Graduate School Courses//ST 558//Blog Update//mikebrad140.github.io//_RMD//2023-06-23-blog-post-number-Project1.Rmd",
  output_format = "github_document",
  output_dir = "C://Users//mbradshaw//OneDrive - Research Triangle Institute//Documents//Graduate School Courses//ST 558//Blog Update//mikebrad140.github.io//_posts",
  output_options = list(keep_html = FALSE, html_preview=FALSE)
)
```  
### Explaining the project and interesting findings

### Reflecting on the process:

#### Most difficult part of the logic and programming for you?

#### What would I do differently in approaching a similar project in the future?



[Link to github pages repo:](https://github.com/mikebrad140/ST558---Project-1)  

[Link to Project 1 non-github pages site:](https://mikebrad140.github.io/ST558---Project-1/)